name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  runhaskell:
    name: Build
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '8.10.7' # Exact version of ghc to use
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
      # You may pin to the exact commit or the version.
      # uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72
      - uses: cachix/install-nix-action@v30
      # Install ghcjs
      - run: nix-channel --add https://nixos.org/channels/nixos-24.05 nixpkgs
      - run: nix-channel --update
      - run: nix-env -iA nixpkgs.haskell.compiler.ghcjs
      # Build command
      - run: cabal build --ghcjs
